fixtures:
  repositories:
    stdlib:
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib'
    concat:
      repo: 'git://github.com/puppetlabs/puppetlabs-concat'
      ref: '2.1.0'
  symlinks:
    'collectd': "#{source_dir}"
